# CLIP Residual Fusion Hyperparameter Tuning

In [1]:
import sys
from pathlib import Path

IN_COLAB = 'google.colab' in sys.modules

if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    PROJECT_ROOT = Path('/content/drive/MyDrive/dissertation')
else:
    PROJECT_ROOT = Path('../../..').resolve()

sys.path.insert(0, str(PROJECT_ROOT))

print(f'IN_COLAB={IN_COLAB}')
print(f'PROJECT_ROOT={PROJECT_ROOT}')

Mounted at /content/drive
IN_COLAB=True
PROJECT_ROOT=/content/drive/MyDrive/dissertation

In [2]:
import hashlib
import json
import time

import numpy as np
import pandas as pd
import torch

from src import dataloader as data
from src import metrics
from src import train
from src.models.classical_baseline import HORIZONS
from src.models.multimodal_residual import load_frozen_baseline, FrozenImageOnlyResidualPredictor

ENCODER_NAME = 'dinov2'
IMG_FEAT_DIM = 768
EXPECTED_IMG_PROJ_DIM = 4

SEEDS = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]

EXP_DIR = PROJECT_ROOT / 'experiments' / '5_residual_hyper'

SHARED_CONFIG_PATH = EXP_DIR / 'shared_search' / 'multimodal_tuning_configurations.csv'

RESULTS_DIR = EXP_DIR / 'results' / ENCODER_NAME
CHECKPOINT_ROOT = EXP_DIR / 'checkpoints' / ENCODER_NAME

BASELINE_CHECKPOINT_DIR = PROJECT_ROOT / 'experiments' / '3_initial_multimodal' / 'multimodal' / 'checkpoints' / 'gated_cgm_time'

BASELINE_RESULTS_DIR = PROJECT_ROOT / 'experiments' / '3_initial_multimodal' / 'multimodal' / 'results' / 'gated_cgm_time'

SEED_RESULT_DIR = RESULTS_DIR / 'seed_results'
SUMMARY_DIR = RESULTS_DIR / 'summary'

for p in [RESULTS_DIR, SEED_RESULT_DIR, SUMMARY_DIR, CHECKPOINT_ROOT]:
    p.mkdir(parents=True, exist_ok=True)

TRIAL_TABLE_PATH = SUMMARY_DIR / 'dinov2_tuning_trials.csv'
BEST_CONFIG_PATH = SUMMARY_DIR / 'dinov2_best_config.json'
PARTICIPANT_TABLE_PATH = SUMMARY_DIR / 'dinov2_selected_config_participant_rmse.csv'

print('Shared configs:', SHARED_CONFIG_PATH)
print('Results:', RESULTS_DIR)

Shared configs: /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/shared_search/multimodal_tuning_configurations.csv
Results: /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/dinov2

In [8]:
configs = pd.read_csv(SHARED_CONFIG_PATH).sort_values('config_order').reset_index(drop=True)

required_cols = {
    'config_order', 'config_id', 'is_anchor',
    'img_proj_dim', 'img_dropout', 'lr', 'weight_decay'
}

expected_anchor = {
    'img_proj_dim': 4,
    'img_dropout': 0.3,
    'lr': 1e-4,
    'weight_decay': 1e-5,
}

anchor_rows = configs[configs['is_anchor'].astype(str).str.lower().isin(['true','1'])]
anchor = anchor_rows.iloc[0]
config_sha256 = hashlib.sha256(SHARED_CONFIG_PATH.read_bytes()).hexdigest()

print(f'Loaded {len(configs)} fixed configurations.')
print('CSV SHA256:', config_sha256)
display(configs)

Loaded 40 fixed configurations.
CSV SHA256: 32e220271d6157119aec540c96162224e751d9f49207f511dc6cb171c77434d3

,config_order,config_id,is_anchor,img_proj_dim,img_dropout,lr,weight_decay
0,1,cfg_01,True,4,0.3,0.00010,0.000010
1,2,cfg_02,False,4,0.1,0.00003,0.000000
2,3,cfg_03,False,4,0.5,0.00003,0.000010
3,4,cfg_04,False,4,0.1,0.00001,0.000001
4,5,cfg_05,False,4,0.3,0.00100,0.000000
5,6,cfg_06,False,4,0.5,0.00100,0.000001
6,7,cfg_07,False,4,0.5,0.00010,0.000001
7,8,cfg_08,False,4,0.1,0.00100,0.000001
8,9,cfg_09,False,4,0.0,0.00010,0.000100
9,10,cfg_10,False,4,0.5,0.00003,0.000100
10,11,cfg_11,False,4,0.0,0.00100,0.000010
11,12,cfg_12,False,4,0.3,0.00003,0.000000
12,13,cfg_13,False,4,0.0,0.00100,0.000100
13,14,cfg_14,False,4,0.5,0.00001,0.000001
14,15,cfg_15,False,4,0.3,0.00001,0.000100
15,16,cfg_16,False,4,0.0,0.00100,0.000001
16,17,cfg_17,False,4,0.0,0.00003,0.000000
17,18,cfg_18,False,4,0.5,0.00030,0.000010
18,19,cfg_19,False,4,0.1,0.00100,0.000100
19,20,cfg_20,False,4,0.3,0.00003,0.000001
20,21,cfg_21,False,4,0.5,0.00030,0.000000
21,22,cfg_22,False,4,0.3,0.00003,0.000010
22,23,cfg_23,False,4,0.0,0.00010,0.000000
23,24,cfg_24,False,4,0.0,0.00030,0.000010
24,25,cfg_25,False,4,0.3,0.00001,0.000001
25,26,cfg_26,False,4,0.1,0.00030,0.000001
26,27,cfg_27,False,4,0.3,0.00030,0.000100
27,28,cfg_28,False,4,0.1,0.00003,0.000001
28,29,cfg_29,False,4,0.3,0.00010,0.000100
29,30,cfg_30,False,4,0.1,0.00010,0.000100
30,31,cfg_31,False,4,0.0,0.00100,0.000000
31,32,cfg_32,False,4,0.0,0.00001,0.000000
32,33,cfg_33,False,4,0.1,0.00001,0.000010
33,34,cfg_34,False,4,0.3,0.00100,0.000010
34,35,cfg_35,False,4,0.3,0.00100,0.000001
35,36,cfg_36,False,4,0.0,0.00003,0.000001
36,37,cfg_37,False,4,0.1,0.00003,0.000010
37,38,cfg_38,False,4,0.1,0.00030,0.000010
38,39,cfg_39,False,4,0.3,0.00001,0.000000
39,40,cfg_40,False,4,0.1,0.00001,0.000000

In [4]:
stats = data.load_cgm_stats()

train_loader = data.load_multimodal_tensors('train', encoder_name=ENCODER_NAME)
val_loader = data.load_multimodal_tensors('val', encoder_name=ENCODER_NAME, shuffle=False)

val_participant_ids = data.load_multimodal_participant_ids('val')
VAL_PARTICIPANT_IDS = sorted(set(val_participant_ids))

print('n_train_batches:', len(train_loader))
print('n_val_batches:', len(val_loader))
print('n_val_samples:', len(val_loader.dataset))
print('validation participants:', VAL_PARTICIPANT_IDS)

sample_batch = next(iter(train_loader))
print('batch shapes:', [tuple(x.shape) for x in sample_batch])

n_train_batches: 323
n_val_batches: 64
n_val_samples: 16355
validation participants: [np.str_('CGMacros-005'), np.str_('CGMacros-016'), np.str_('CGMacros-027'), np.str_('CGMacros-044'), np.str_('CGMacros-046'), np.str_('CGMacros-048')]
batch shapes: [(256, 24), (256,), (256,), (256, 768), (256, 5)]

In [5]:
def forward_fn(model, batch, device):
    cgm, tsm, has_meal, img_feat, target = batch
    pred = model(cgm.to(device), tsm.to(device), img_feat.to(device), has_meal.to(device))
    return pred, target.to(device)


def h_entry(d, h):
    if str(h) in d:
        return d[str(h)]
    if h in d:
        return d[h]
    raise KeyError(f'Horizon {h} not found. Keys={list(d.keys())}')


def p_entry(d, pid):
    if str(pid) in d:
        return d[str(pid)]
    if pid in d:
        return d[pid]
    raise KeyError(f'Participant {pid} not found. Keys={list(d.keys())}')


def result_path(config_id, seed):
    return SEED_RESULT_DIR / f'{config_id}__seed{seed}.json'

In [6]:
baseline_by_seed = {}

for seed in SEEDS:
    path = BASELINE_RESULTS_DIR / f'gated_cgm_time_seed{seed}_results.json'
    if not path.exists():
        raise FileNotFoundError(f'Missing baseline result: {path}')

    with open(path) as f:
        r = json.load(f)

    baseline_by_seed[seed] = {
        int(h): float(h_entry(r['val_results'], h)['rmse'])
        for h in HORIZONS
    }

baseline_df = pd.DataFrame.from_dict(baseline_by_seed, orient='index')
baseline_df.index.name = 'seed'
baseline_df.columns = [f'rmse_{h}' for h in baseline_df.columns]

display(baseline_df.round(4))

      rmse_15  rmse_30  rmse_60  rmse_90  rmse_120
seed
7     10.5760  16.6694  24.0796  28.4527   31.2947
14    10.6479  16.7263  24.1044  28.3922   31.2335
21    10.5938  16.6580  24.0522  28.3216   31.1125
28    10.4778  16.5493  23.9988  28.4047   31.2741
35    10.4813  16.6073  24.1134  28.4409   31.2625
42    10.5140  16.6368  23.9722  28.3538   31.2148
49    10.6880  16.7477  24.0997  28.3797   31.1949
56    10.6339  16.7684  24.1647  28.4863   31.2816
63    10.5760  16.7480  24.0524  28.3896   31.2817
70    10.5711  16.6938  24.0569  28.3918   31.3112

In [9]:
CHECK_SEED = SEEDS[0]
CHECK_DROPOUT = float(anchor['img_dropout'])

base_model = load_frozen_baseline(
    CHECK_SEED,
    BASELINE_CHECKPOINT_DIR,
)

train.set_seed(CHECK_SEED)

check_model = FrozenImageOnlyResidualPredictor(
    base_model=base_model,
    img_feat_dim=IMG_FEAT_DIM,
    img_proj_dim=EXPECTED_IMG_PROJ_DIM,
    img_dropout=CHECK_DROPOUT,
)

baseline_trainable = [
    name for name, p in check_model.named_parameters()
    if p.requires_grad and (
        name.startswith('gru.')
        or name.startswith('time_proj.')
        or name.startswith('base_head.')
    )
]
if baseline_trainable:
    raise RuntimeError(f'Frozen baseline contains trainable parameters: {baseline_trainable}')

trainable_names = [name for name, p in check_model.named_parameters() if p.requires_grad]
print('Trainable parameters:')
for name in trainable_names:
    print(' ', name)

batch = next(iter(val_loader))
cgm, tsm, has_meal, img_feat, _ = batch

check_model.eval()
base_model.eval()
with torch.no_grad():
    base_pred = base_model(cgm, tsm, has_meal)
    residual_pred = check_model(cgm, tsm, img_feat, has_meal)

init_diff = (base_pred - residual_pred).abs().max().item()
print(f'Initial max |residual - baseline| = {init_diff:.8f}')

if init_diff > 1e-5:
    raise RuntimeError(f'Residual initialisation sanity check failed: {init_diff}')

print('Sanity checks passed.')

Trainable parameters:
  img_proj.0.weight
  img_proj.0.bias
  image_head.0.weight
  image_head.0.bias
  image_head.3.weight
  image_head.3.bias
Initial max |residual - baseline| = 0.00000000
Sanity checks passed.

In [11]:
batch = next(iter(train_loader))
cgm, tsm, has_meal, img_feat, target = batch

print('Encoder:', ENCODER_NAME)
print('Image feature shape:', img_feat.shape)

assert ENCODER_NAME == 'dinov2'
assert img_feat.shape[-1] == IMG_FEAT_DIM == 768

Encoder: dinov2
Image feature shape: torch.Size([256, 768])

In [12]:
for config_idx, row in configs.iterrows():

    config_id = str(row['config_id'])
    img_proj_dim = int(row['img_proj_dim'])
    img_dropout = float(row['img_dropout'])
    lr = float(row['lr'])
    weight_decay = float(row['weight_decay'])

    print('\n' + '=' * 90)
    print(
        f'{config_id} ({config_idx + 1}/{len(configs)}) | '
        f'd={img_proj_dim} | dropout={img_dropout:g} | '
        f'lr={lr:g} | wd={weight_decay:g}'
    )
    print('=' * 90)

    for seed in SEEDS:

        save_path = result_path(config_id, seed)

        if save_path.exists():
            print(f'  seed={seed}: already complete')
            continue

        print(f'  seed={seed}: training')

        base_model = load_frozen_baseline(seed, BASELINE_CHECKPOINT_DIR)

        train.set_seed(seed)

        model = FrozenImageOnlyResidualPredictor(
            base_model=base_model, img_feat_dim=IMG_FEAT_DIM, img_proj_dim=img_proj_dim, img_dropout=img_dropout)

        baseline_trainable = [name for name, p in model.named_parameters()
                              if p.requires_grad and name.startswith(('gru.', 'time_proj.', 'base_head.'))]
        if baseline_trainable:
            raise RuntimeError(
                f'{config_id}, seed={seed}: baseline not fully frozen: '
                f'{baseline_trainable}'
            )

        # Verify zero-residual initialisation for every run.
        batch = next(iter(val_loader))
        cgm, tsm, has_meal, img_feat, _ = batch

        model.eval()
        base_model.eval()
        with torch.no_grad():
            base_pred = base_model(cgm, tsm, has_meal)
            residual_pred = model(cgm, tsm, img_feat, has_meal)

        init_diff = (base_pred - residual_pred).abs().max().item()
        if init_diff > 1e-5:
            raise RuntimeError(
                f'{config_id}, seed={seed}: initial residual != baseline '
                f'(max diff={init_diff})'
            )

        checkpoint_dir = CHECKPOINT_ROOT / config_id / f'seed_{seed}'

        t0 = time.time()

        model, history = train.train_model(
            model, train_loader, val_loader, stats['cgm_mean'], stats['cgm_std'], lr=lr, weight_decay=weight_decay,
            forward_fn=forward_fn, checkpoint_dir=checkpoint_dir, verbose=False, progress_bar=True, progress_desc=f'DINOv2 {config_id} seed={seed}')

        elapsed_seconds = time.time() - t0

        best_epoch = int(np.argmin(history['val_loss']) + 1)
        n_epochs_trained = int(len(history['train_loss']))

        y_pred_val, y_true_val = train.predict(model, val_loader, forward_fn=forward_fn)

        overall_val = metrics.evaluate(y_pred_val, y_true_val, stats['cgm_mean'], stats['cgm_std'])

        per_participant_val = metrics.evaluate_per_participant(
            y_pred_val, y_true_val, val_participant_ids, stats['cgm_mean'], stats['cgm_std'])

        # Ensure all expected validation participants were produced.
        for pid in VAL_PARTICIPANT_IDS:
            _ = p_entry(per_participant_val, pid)

        payload = {
            'encoder': ENCODER_NAME,
            'config_id': config_id,
            'config_order': int(row['config_order']),
            'is_anchor': bool(str(row['is_anchor']).lower() in ['true', '1']),
            'shared_config_sha256': config_sha256,
            'seed': int(seed),
            'hyperparameters': {
                'img_proj_dim': img_proj_dim,
                'img_dropout': img_dropout,
                'lr': lr,
                'weight_decay': weight_decay,
            },
            'initial_max_abs_diff_vs_baseline': float(init_diff),
            'best_epoch': best_epoch,
            'n_epochs_trained': n_epochs_trained,
            'elapsed_seconds': float(elapsed_seconds),
            'val_results': overall_val,
            'val_results_per_participant': per_participant_val,
        }

        with open(save_path, 'w') as f:
            json.dump(payload, f, indent=2)

        print(
            f'    saved | best_epoch={best_epoch} | '
            f'{elapsed_seconds/60:.1f} min'
        )

print('\nAll requested DINOv2 tuning runs are complete.')

==========================================================================================
cfg_01 (1/40) | d=4 | dropout=0.3 | lr=0.0001 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_01 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min

==========================================================================================
cfg_02 (2/40) | d=4 | dropout=0.1 | lr=3e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=30 | 0.8 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=29 | 0.8 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_02 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_03 (3/40) | d=4 | dropout=0.5 | lr=3e-05 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=13 | 0.5 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=35 | 0.9 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=46 | 1.0 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=43 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=29 | 0.8 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_03 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=37 | 0.9 min

==========================================================================================
cfg_04 (4/40) | d=4 | dropout=0.1 | lr=1e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=13 | 0.5 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_04 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min

==========================================================================================
cfg_05 (5/40) | d=4 | dropout=0.3 | lr=0.001 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_05 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min

==========================================================================================
cfg_06 (6/40) | d=4 | dropout=0.5 | lr=0.001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.5 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_06 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=21 | 0.6 min

==========================================================================================
cfg_07 (7/40) | d=4 | dropout=0.5 | lr=0.0001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=32 | 0.9 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=13 | 0.5 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_07 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min

==========================================================================================
cfg_08 (8/40) | d=4 | dropout=0.1 | lr=0.001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_08 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_09 (9/40) | d=4 | dropout=0 | lr=0.0001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_09 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_10 (10/40) | d=4 | dropout=0.5 | lr=3e-05 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=13 | 0.5 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=35 | 0.9 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=37 | 0.9 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=35 | 0.9 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=29 | 0.8 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_10 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=46 | 1.0 min

==========================================================================================
cfg_11 (11/40) | d=4 | dropout=0 | lr=0.001 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_11 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_12 (12/40) | d=4 | dropout=0.3 | lr=3e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=47 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.6 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=18 | 0.6 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_12 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min

==========================================================================================
cfg_13 (13/40) | d=4 | dropout=0 | lr=0.001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_13 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_14 (14/40) | d=4 | dropout=0.5 | lr=1e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=37 | 1.0 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=49 | 1.0 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=17 | 0.5 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=20 | 0.6 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_14 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=25 | 0.7 min

==========================================================================================
cfg_15 (15/40) | d=4 | dropout=0.3 | lr=1e-05 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=17 | 0.5 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=21 | 0.6 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.7 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=17 | 0.5 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_15 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min

==========================================================================================
cfg_16 (16/40) | d=4 | dropout=0 | lr=0.001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_16 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_17 (17/40) | d=4 | dropout=0 | lr=3e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=19 | 0.6 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_17 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_18 (18/40) | d=4 | dropout=0.5 | lr=0.0003 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_18 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min

==========================================================================================
cfg_19 (19/40) | d=4 | dropout=0.1 | lr=0.001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_19 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_20 (20/40) | d=4 | dropout=0.3 | lr=3e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.7 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=18 | 0.6 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_20 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min

==========================================================================================
cfg_21 (21/40) | d=4 | dropout=0.5 | lr=0.0003 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_21 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min

==========================================================================================
cfg_22 (22/40) | d=4 | dropout=0.3 | lr=3e-05 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=21 | 0.6 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.6 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=18 | 0.6 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_22 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min

==========================================================================================
cfg_23 (23/40) | d=4 | dropout=0 | lr=0.0001 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_23 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_24 (24/40) | d=4 | dropout=0 | lr=0.0003 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_24 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_25 (25/40) | d=4 | dropout=0.3 | lr=1e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=21 | 0.6 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.6 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=17 | 0.5 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=18 | 0.6 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_25 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min

==========================================================================================
cfg_26 (26/40) | d=4 | dropout=0.1 | lr=0.0003 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_26 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.3 min

==========================================================================================
cfg_27 (27/40) | d=4 | dropout=0.3 | lr=0.0003 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_27 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_28 (28/40) | d=4 | dropout=0.1 | lr=3e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=34 | 0.9 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_28 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_29 (29/40) | d=4 | dropout=0.3 | lr=0.0001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_29 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min

==========================================================================================
cfg_30 (30/40) | d=4 | dropout=0.1 | lr=0.0001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_30 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min

==========================================================================================
cfg_31 (31/40) | d=4 | dropout=0 | lr=0.001 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_31 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_32 (32/40) | d=4 | dropout=0 | lr=1e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=30 | 0.8 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=13 | 0.5 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_32 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min

==========================================================================================
cfg_33 (33/40) | d=4 | dropout=0.1 | lr=1e-05 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=17 | 0.6 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=13 | 0.5 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_33 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min

==========================================================================================
cfg_34 (34/40) | d=4 | dropout=0.3 | lr=0.001 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_34 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min

==========================================================================================
cfg_35 (35/40) | d=4 | dropout=0.3 | lr=0.001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_35 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_36 (36/40) | d=4 | dropout=0 | lr=3e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=19 | 0.6 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_36 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_37 (37/40) | d=4 | dropout=0.1 | lr=3e-05 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=34 | 0.9 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_37 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_38 (38/40) | d=4 | dropout=0.1 | lr=0.0003 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_38 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_39 (39/40) | d=4 | dropout=0.3 | lr=1e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=21 | 0.6 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.6 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=17 | 0.5 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=18 | 0.6 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_39 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min

==========================================================================================
cfg_40 (40/40) | d=4 | dropout=0.1 | lr=1e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=13 | 0.5 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,029,502

DINOv2 cfg_40 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min

All requested DINOv2 tuning runs are complete.

In [13]:
trial_rows = []
participant_rows_all = []

for _, cfg in configs.iterrows():

    config_id = str(cfg['config_id'])
    seed_results = []

    for seed in SEEDS:
        with open(result_path(config_id, seed)) as f:
            r = json.load(f)

        if r.get('shared_config_sha256') != config_sha256:
            raise RuntimeError(
                f'{config_id}, seed={seed} was produced from a different '
                'shared configuration file.'
            )

        seed_results.append(r)

    row = {
        'config_order': int(cfg['config_order']),
        'config_id': config_id,
        'is_anchor': bool(str(cfg['is_anchor']).lower() in ['true', '1']),
        'img_proj_dim': int(cfg['img_proj_dim']),
        'img_dropout': float(cfg['img_dropout']),
        'lr': float(cfg['lr']),
        'weight_decay': float(cfg['weight_decay']),
    }

    all_relative_improvements = []
    improved_horizon_seed_pairs = 0
    all_absolute_rmses = []

    for h in HORIZONS:

        candidate = np.asarray([float(h_entry(r['val_results'], h)['rmse']) for r in seed_results])

        baseline = np.asarray([baseline_by_seed[seed][int(h)] for seed in SEEDS])

        improvement_pct = (baseline - candidate) / baseline * 100.0

        # Participant means across seeds, then SD across participants.
        participant_means = []

        for pid in VAL_PARTICIPANT_IDS:
            pid_seed_rmses = [
                float(h_entry(p_entry(r['val_results_per_participant'], pid), h)['rmse']) for r in seed_results]

            pid_mean = float(np.mean(pid_seed_rmses))
            participant_means.append(pid_mean)

            participant_rows_all.append({
                'config_id': config_id,
                'participant_id': pid,
                'horizon': int(h),
                'mean_rmse_across_seeds': pid_mean,
                'sd_rmse_across_seeds': float(np.std(pid_seed_rmses, ddof=1)),
            })

        rmse_mean = float(np.mean(candidate))
        sd1 = float(np.std(candidate, ddof=1))
        sd2 = float(np.std(participant_means, ddof=1))
        wins = int(np.sum(candidate < baseline))

        row[f'rmse_{h}'] = rmse_mean
        row[f'sd1_{h}'] = sd1
        row[f'sd2_{h}'] = sd2
        row[f'improvement_pct_{h}'] = float(np.mean(improvement_pct))
        row[f'improved_seeds_{h}'] = wins

        all_relative_improvements.extend(improvement_pct.tolist())
        improved_horizon_seed_pairs += wins
        all_absolute_rmses.extend(candidate.tolist())

    row['mean_relative_improvement_pct'] = float(
        np.mean(all_relative_improvements)
    )
    row['improved_horizon_seed_pairs'] = int(improved_horizon_seed_pairs)
    row['mean_validation_rmse'] = float(np.mean(all_absolute_rmses))

    trial_rows.append(row)

trial_df = pd.DataFrame(trial_rows)
participant_df = pd.DataFrame(participant_rows_all)

trial_df.to_csv(TRIAL_TABLE_PATH, index=False)

print('Saved complete tuning table:')
print(TRIAL_TABLE_PATH)

display(
    trial_df[
        [
            'config_order','config_id','is_anchor',
            'img_dropout','lr','weight_decay',
            'mean_relative_improvement_pct',
            'improved_horizon_seed_pairs',
            'mean_validation_rmse',
            *[f'rmse_{h}' for h in HORIZONS],
        ]
    ].round(5)
)

Saved complete tuning table:
/content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/dinov2/summary/dinov2_tuning_trials.csv

,config_order,config_id,is_anchor,img_dropout,lr,weight_decay,mean_relative_improvement_pct,improved_horizon_seed_pairs,mean_validation_rmse,rmse_15,rmse_30,rmse_60,rmse_90,rmse_120
0,1,cfg_01,True,0.3,0.00010,0.00001,0.64482,50,22.03712,10.54401,16.59030,23.88123,28.17578,30.99430
1,2,cfg_02,False,0.1,0.00003,0.00000,0.54845,50,22.05857,10.54833,16.60985,23.92918,28.21220,30.99329
2,3,cfg_03,False,0.5,0.00003,0.00001,0.51839,50,22.06717,10.54964,16.61200,23.92648,28.21636,31.03136
3,4,cfg_04,False,0.1,0.00001,0.00000,0.45750,48,22.08174,10.55110,16.62098,23.95491,28.24560,31.03612
4,5,cfg_05,False,0.3,0.00100,0.00000,0.72251,50,22.01536,10.54389,16.58717,23.86185,28.13624,30.94765
5,6,cfg_06,False,0.5,0.00100,0.00000,0.62244,50,22.04004,10.54763,16.60205,23.89207,28.17358,30.98487
6,7,cfg_07,False,0.5,0.00010,0.00000,0.60199,50,22.04601,10.54716,16.60207,23.89901,28.18334,30.99846
7,8,cfg_08,False,0.1,0.00100,0.00000,0.52716,48,22.06823,10.54751,16.59762,23.91391,28.22991,31.05222
8,9,cfg_09,False,0.0,0.00010,0.00010,0.52047,50,22.06558,10.54946,16.61248,23.93806,28.22636,31.00153
9,10,cfg_10,False,0.5,0.00003,0.00010,0.54285,50,22.06049,10.54961,16.61103,23.91764,28.20381,31.02035
10,11,cfg_11,False,0.0,0.00100,0.00001,0.48492,48,22.07677,10.55278,16.60985,23.91931,28.23731,31.06460
11,12,cfg_12,False,0.3,0.00003,0.00000,0.51631,50,22.06709,10.55022,16.61318,23.93007,28.22043,31.02155
12,13,cfg_13,False,0.0,0.00100,0.00010,0.38399,42,22.10392,10.55378,16.61888,23.94513,28.28121,31.12058
13,14,cfg_14,False,0.5,0.00001,0.00000,0.38578,50,22.10037,10.55409,16.62891,23.96744,28.26959,31.08180
14,15,cfg_15,False,0.3,0.00001,0.00010,0.45305,50,22.08359,10.55066,16.61971,23.95253,28.24879,31.04625
15,16,cfg_16,False,0.0,0.00100,0.00000,0.39905,40,22.10055,10.55221,16.61549,23.94493,28.27798,31.11215
16,17,cfg_17,False,0.0,0.00003,0.00000,0.50591,50,22.06881,10.55027,16.61608,23.94353,28.22881,31.00537
17,18,cfg_18,False,0.5,0.00030,0.00001,0.62500,50,22.04100,10.54556,16.59625,23.89142,28.17858,30.99317
18,19,cfg_19,False,0.1,0.00100,0.00010,0.69055,50,22.02523,10.54380,16.58480,23.86604,28.15359,30.97793
19,20,cfg_20,False,0.3,0.00003,0.00000,0.51396,50,22.06756,10.55040,16.61374,23.93126,28.22126,31.02115
20,21,cfg_21,False,0.5,0.00030,0.00000,0.63314,50,22.03844,10.54581,16.59723,23.88897,28.17324,30.98698
21,22,cfg_22,False,0.3,0.00003,0.00001,0.51271,50,22.06796,10.55039,16.61371,23.93106,28.22162,31.02302
22,23,cfg_23,False,0.0,0.00010,0.00000,0.56845,50,22.05368,10.54694,16.60593,23.92762,28.20950,30.97839
23,24,cfg_24,False,0.0,0.00030,0.00001,0.36132,45,22.11029,10.54910,16.62004,23.97911,28.29613,31.10708
24,25,cfg_25,False,0.3,0.00001,0.00000,0.44921,50,22.08429,10.55127,16.62079,23.95353,28.24977,31.04608
25,26,cfg_26,False,0.1,0.00030,0.00000,0.47754,50,22.07942,10.54775,16.60857,23.94570,28.24896,31.04613
26,27,cfg_27,False,0.3,0.00030,0.00010,0.66786,50,22.03068,10.54401,16.58856,23.87643,28.16678,30.97761
27,28,cfg_28,False,0.1,0.00003,0.00000,0.52932,50,22.06317,10.54905,16.61335,23.93484,28.21856,31.00002
28,29,cfg_29,False,0.3,0.00010,0.00010,0.63053,50,22.04059,10.54448,16.59264,23.88607,28.18123,30.99853
29,30,cfg_30,False,0.1,0.00010,0.00010,0.57722,50,22.05218,10.54630,16.60334,23.92095,28.20139,30.98894
30,31,cfg_31,False,0.0,0.00100,0.00000,0.36329,40,22.10970,10.55434,16.61772,23.95075,28.29920,31.12649
31,32,cfg_32,False,0.0,0.00001,0.00000,0.44660,48,22.08394,10.55247,16.62352,23.95809,28.24826,31.03735
32,33,cfg_33,False,0.1,0.00001,0.00001,0.45762,48,22.08164,10.55123,16.62099,23.95512,28.24547,31.03541
33,34,cfg_34,False,0.3,0.00100,0.00001,0.74172,50,22.01173,10.54172,16.58242,23.85203,28.13051,30.95199
34,35,cfg_35,False,0.3,0.00100,0.00000,0.72165,50,22.01640,10.54264,16.58521,23.86299,28.13861,30.95253
35,36,cfg_36,False,0.0,0.00003,0.00000,0.50476,50,22.06910,10.55033,16.61621,23.94380,28.22929,31.00586
36,37,cfg_37,False,0.1,0.00003,0.00001,0.53407,50,22.06200,10.54889,16.61273,23.93310,28.21665,30.99862
37,38,cfg_38,False,0.1,0.00030,0.00001,0.50472,50,22.07378,10.54417,16.60270,23.94095,28.24236,31.03871
38,39,cfg_39,False,0.3,0.00001,0.00000,0.44926,50,22.08427,10.55128,16.62081,23.95353,28.24974,31.04600
39,40,cfg_40,False,0.1,0.00001,0.00000,0.45674,48,22.08193,10.55112,16.62106,23.95515,28.24590,31.03644

In [14]:
ranked_df = trial_df.sort_values(
    by=['mean_relative_improvement_pct', 'improved_horizon_seed_pairs', 'mean_validation_rmse', 'config_order'],
    ascending=[False, False, True, True]).reset_index(drop=True)

ranked_df.insert(0, 'rank', np.arange(1, len(ranked_df) + 1))

display(
    ranked_df[
        [
            'rank','config_id','is_anchor',
            'img_dropout','lr','weight_decay',
            'mean_relative_improvement_pct',
            'improved_horizon_seed_pairs',
            'mean_validation_rmse',
            *[f'rmse_{h}' for h in HORIZONS],
            *[f'sd1_{h}' for h in HORIZONS],
            *[f'sd2_{h}' for h in HORIZONS],
        ]
    ].round(5)
)

best = ranked_df.iloc[0]
best_config_id = str(best['config_id'])

best_payload = {
    'encoder': ENCODER_NAME,
    'shared_config_sha256': config_sha256,
    'selection_data': 'validation only',
    'selection_rule': {
        'primary': (
            'maximise mean relative RMSE improvement versus seed-matched '
            'CGM+Time across all five horizons and ten seeds'
        ),
        'tie_breaker_1': 'maximise improved horizon-seed pairs',
        'tie_breaker_2': 'minimise mean validation RMSE',
        'tie_breaker_3': 'lower config_order',
    },
    'selected': {
        'config_id': best_config_id,
        'config_order': int(best['config_order']),
        'img_proj_dim': int(best['img_proj_dim']),
        'img_dropout': float(best['img_dropout']),
        'lr': float(best['lr']),
        'weight_decay': float(best['weight_decay']),
        'mean_relative_improvement_pct': float(best['mean_relative_improvement_pct']),
        'improved_horizon_seed_pairs': int(best['improved_horizon_seed_pairs']),
        'mean_validation_rmse': float(best['mean_validation_rmse']),
    },
    'horizons': {},
}

for h in HORIZONS:
    best_payload['horizons'][str(h)] = {
        'rmse_mean': float(best[f'rmse_{h}']),
        'sd1_across_seeds': float(best[f'sd1_{h}']),
        'sd2_across_participants': float(best[f'sd2_{h}']),
        'mean_improvement_pct_vs_cgm_time': float(best[f'improvement_pct_{h}']),
        'improved_seeds_vs_cgm_time': int(best[f'improved_seeds_{h}']),
    }

with open(BEST_CONFIG_PATH, 'w') as f:
    json.dump(best_payload, f, indent=2)

selected_participant_df = participant_df[participant_df['config_id'] == best_config_id].copy()

selected_participant_df.to_csv(PARTICIPANT_TABLE_PATH, index=False)

print('\n=== SELECTED CLIP CONFIGURATION ===')
print('config_id:', best_config_id)
print('dropout:', best['img_dropout'])
print('lr:', best['lr'])
print('weight_decay:', best['weight_decay'])
print(
    'mean relative improvement:',
    f"{best['mean_relative_improvement_pct']:.4f}%"
)
print(
    'improved horizon-seed pairs:',
    f"{int(best['improved_horizon_seed_pairs'])}/{len(HORIZONS)*len(SEEDS)}"
)

print('\nPer-horizon validation result: mean ± sd1 (sd2)')
for h in HORIZONS:
    print(
        f'{h:>3} min: '
        f"{best[f'rmse_{h}']:.3f} ± "
        f"{best[f'sd1_{h}']:.3f} "
        f"({best[f'sd2_{h}']:.3f}) | "
        f"improvement={best[f'improvement_pct_{h}']:.3f}% | "
        f"better seeds={int(best[f'improved_seeds_{h}'])}/{len(SEEDS)}"
    )

print('\nSaved:')
print(' ', TRIAL_TABLE_PATH)
print(' ', BEST_CONFIG_PATH)
print(' ', PARTICIPANT_TABLE_PATH)

,rank,config_id,is_anchor,img_dropout,lr,weight_decay,mean_relative_improvement_pct,improved_horizon_seed_pairs,mean_validation_rmse,rmse_15,...,sd1_15,sd1_30,sd1_60,sd1_90,sd1_120,sd2_15,sd2_30,sd2_60,sd2_90,sd2_120
0,1,cfg_34,False,0.3,0.00100,0.00001,0.74172,50,22.01173,10.54172,...,0.05632,0.07712,0.09742,0.12415,0.13418,2.09819,3.63782,6.94390,10.06035,11.86373
1,2,cfg_05,False,0.3,0.00100,0.00000,0.72251,50,22.01536,10.54389,...,0.05773,0.07284,0.09532,0.11518,0.12287,2.09507,3.62709,6.90810,10.01312,11.81270
2,3,cfg_35,False,0.3,0.00100,0.00000,0.72165,50,22.01640,10.54264,...,0.05917,0.08180,0.09677,0.11678,0.13484,2.09505,3.62806,6.93242,10.05167,11.86782
3,4,cfg_19,False,0.1,0.00100,0.00010,0.69055,50,22.02523,10.54380,...,0.05307,0.07054,0.08027,0.11571,0.16122,2.09216,3.61492,6.85237,9.93351,11.73295
4,5,cfg_27,False,0.3,0.00030,0.00010,0.66786,50,22.03068,10.54401,...,0.05526,0.06224,0.05657,0.04622,0.07376,2.09326,3.62950,6.94452,10.07337,11.89684
5,6,cfg_01,True,0.3,0.00010,0.00001,0.64482,50,22.03712,10.54401,...,0.05740,0.06668,0.07513,0.07192,0.06337,2.09232,3.62780,6.95182,10.09233,11.92573
6,7,cfg_21,False,0.5,0.00030,0.00000,0.63314,50,22.03844,10.54581,...,0.05763,0.06682,0.05694,0.06035,0.06909,2.09303,3.62705,6.96598,10.11944,11.95657
7,8,cfg_29,False,0.3,0.00010,0.00010,0.63053,50,22.04059,10.54448,...,0.05751,0.06648,0.08007,0.06708,0.05910,2.09251,3.62836,6.95375,10.09213,11.92376
8,9,cfg_18,False,0.5,0.00030,0.00001,0.62500,50,22.04100,10.54556,...,0.05573,0.06370,0.06244,0.06233,0.07352,2.09454,3.63039,6.97079,10.12204,11.95633
9,10,cfg_06,False,0.5,0.00100,0.00000,0.62244,50,22.04004,10.54763,...,0.05787,0.06769,0.04495,0.06009,0.08380,2.09150,3.61618,6.94761,10.10173,11.93729
10,11,cfg_07,False,0.5,0.00010,0.00000,0.60199,50,22.04601,10.54716,...,0.05836,0.07025,0.07257,0.06452,0.07706,2.09267,3.62363,6.96196,10.11216,11.94458
11,12,cfg_30,False,0.1,0.00010,0.00010,0.57722,50,22.05218,10.54630,...,0.05805,0.07033,0.07748,0.08481,0.09737,2.09524,3.63149,6.93822,10.08063,11.90711
12,13,cfg_23,False,0.0,0.00010,0.00000,0.56845,50,22.05368,10.54694,...,0.06070,0.06968,0.07556,0.08991,0.10287,2.09111,3.62820,6.99397,10.15398,11.98083
13,14,cfg_02,False,0.1,0.00003,0.00000,0.54845,50,22.05857,10.54833,...,0.06158,0.07368,0.08212,0.07531,0.08289,2.09058,3.62272,6.96487,10.12566,11.95716
14,15,cfg_10,False,0.5,0.00003,0.00010,0.54285,50,22.06049,10.54961,...,0.06111,0.07585,0.08827,0.08194,0.07185,2.09329,3.62786,7.00683,10.18696,12.03275
15,16,cfg_37,False,0.1,0.00003,0.00001,0.53407,50,22.06200,10.54889,...,0.06081,0.07135,0.07256,0.07127,0.08737,2.08984,3.62003,6.96159,10.12289,11.95442
16,17,cfg_28,False,0.1,0.00003,0.00000,0.52932,50,22.06317,10.54905,...,0.06092,0.07140,0.07067,0.06645,0.08257,2.08971,3.62039,6.96097,10.12167,11.95291
17,18,cfg_08,False,0.1,0.00100,0.00000,0.52716,48,22.06823,10.54751,...,0.05501,0.06845,0.08090,0.14474,0.21249,2.09590,3.62652,6.89241,10.00256,11.81441
18,19,cfg_09,False,0.0,0.00010,0.00010,0.52047,50,22.06558,10.54946,...,0.06055,0.07030,0.06667,0.08250,0.10674,2.08991,3.62869,7.00899,10.18547,12.02382
19,20,cfg_03,False,0.5,0.00003,0.00001,0.51839,50,22.06717,10.54964,...,0.06103,0.07539,0.08503,0.07635,0.07600,2.09334,3.62889,7.00659,10.18473,12.02973
20,21,cfg_12,False,0.3,0.00003,0.00000,0.51631,50,22.06709,10.55022,...,0.06207,0.07858,0.09616,0.07201,0.05942,2.09273,3.63001,7.01080,10.19201,12.03801
21,22,cfg_20,False,0.3,0.00003,0.00000,0.51396,50,22.06756,10.55040,...,0.06189,0.07771,0.09413,0.07158,0.06105,2.09237,3.62924,7.01110,10.19268,12.03923
22,23,cfg_22,False,0.3,0.00003,0.00001,0.51271,50,22.06796,10.55039,...,0.06171,0.07751,0.09417,0.06970,0.05803,2.09256,3.62946,7.01088,10.19287,12.03976
23,24,cfg_17,False,0.0,0.00003,0.00000,0.50591,50,22.06881,10.55027,...,0.06258,0.07258,0.06610,0.06131,0.07134,2.08864,3.61801,6.96713,10.13517,11.96898
24,25,cfg_36,False,0.0,0.00003,0.00000,0.50476,50,22.06910,10.55033,...,0.06261,0.07259,0.06592,0.06084,0.07069,2.08859,3.61803,6.96758,10.13583,11.96974
25,26,cfg_38,False,0.1,0.00030,0.00001,0.50472,50,22.07378,10.54417,...,0.05885,0.07497,0.07327,0.09549,0.12146,2.09272,3.63535,6.94851,10.08984,11.92246
26,27,cfg_11,False,0.0,0.00100,0.00001,0.48492,48,22.07677,10.55278,...,0.05735,0.09078,0.13562,0.15240,0.17462,2.08592,3.58797,6.78682,9.86626,11.68042
27,28,cfg_26,False,0.1,0.00030,0.00000,0.47754,50,22.07942,10.54775,...,0.05890,0.06943,0.06679,0.09127,0.12086,2.09071,3.62666,6.92449,10.04996,11.87917
28,29,cfg_33,False,0.1,0.00001,0.00001,0.45762,48,22.08164,10.55123,...,0.06061,0.08081,0.07285,0.07380,0.10387,2.08928,3.62504,7.00489,10.18841,12.03160
29,30,cfg_04,False,0.1,0.00001,0.00000,0.45750,48,22.08174,10.55110,...,0.06076,0.08080,0.07320,0.07381,0.10332,2.08922,3.62416,7.00349,10.18745,12.03072
30,31,cfg_40,False,0.1,0.00001,0.00000,0.45674,48,22.08193,10.55112,...,0.06074,0.08076,0.07297,0.07352,0.10312,2.08925,3.62420,7.00352,10.18756,12.03087
31,32,cfg_15,False,0.3,0.00001,0.00010,0.45305,50,22.08359,10.55066,...,0.05936,0.06997,0.05697,0.04229,0.05865,2.09162,3.62843,7.02845,10.22207,12.07183
32,33,cfg_39,False,0.3,0.00001,0.00000,0.44926,50,22.08427,10.55128,...,0.06008,0.07080,0.05763,0.04247,0.05827,2.09147,3.62790,7.02899,10.22340,12.07247
33,34,cfg_25,False,0.3,0.00001,0.00000,0.44921,50,22.08429,10.55127,...,0.06009,0.07081,0.05766,0.04259,0.05840,2.09146,3.62789,7.02892,10.22331,12.07240
34,35,cfg_32,False,0.0,0.00001,0.00000,0.44660,48,22.08394,10.55247,...,0.06197,0.08191,0.07247,0.07258,0.10179,2.08832,3.62227,6.99939,10.18490,12.02799
35,36,cfg_16,False,0.0,0.00100,0.00000,0.39905,40,22.10055,10.55221,...,0.06329,0.10074,0.14086,0.15714,0.16515,2.09173,3.60292,6.78950,9.85290,11.66022
36,37,cfg_14,False,0.5,0.00001,0.00000,0.38578,50,22.10037,10.55409,...,0.06027,0.07149,0.05508,0.04418,0.06865,2.09185,3.62612,7.03660,10.24182,12.09934
37,38,cfg_13,False,0.0,0.00100,0.00010,0.38399,42,22.10392,10.55378,...,0.05757,0.09288,0.15742,0.16568,0.17019,2.08848,3.59147,6.78675,9.86682,11.69262
38,39,cfg_31,False,0.0,0.00100,0.00000,0.36329,40,22.10970,10.55434,...,0.05992,0.09907,0.16254,0.22036,0.24106,2.08803,3.58511,6.75863,9.81954,11.63307
39,40,cfg_24,False,0.0,0.00030,0.00001,0.36132,45,22.11029,10.54910,...,0.06059,0.07889,0.09688,0.13473,0.14185,2.09791,3.64088,6.93450,10.08136,11.91755

=== SELECTED CLIP CONFIGURATION ===
config_id: cfg_34
dropout: 0.3
lr: 0.001
weight_decay: 1e-05
mean relative improvement: 0.7417%
improved horizon-seed pairs: 50/50

Per-horizon validation result: mean ± sd1 (sd2)
 15 min: 10.542 ± 0.056 (2.098) | improvement=0.323% | better seeds=10/10
 30 min: 16.582 ± 0.077 (3.638) | improvement=0.588% | better seeds=10/10
 60 min: 23.852 ± 0.097 (6.944) | improvement=0.903% | better seeds=10/10
 90 min: 28.131 ± 0.124 (10.060) | improvement=0.953% | better seeds=10/10
120 min: 30.952 ± 0.134 (11.864) | improvement=0.942% | better seeds=10/10

Saved:
  /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/dinov2/summary/dinov2_tuning_trials.csv
  /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/dinov2/summary/dinov2_best_config.json
  /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/dinov2/summary/dinov2_selected_config_participant_rmse.csv