# Resnet18 Residual Fusion Hyperparameter Tuning

In [1]:
import sys
from pathlib import Path

IN_COLAB = 'google.colab' in sys.modules

if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    PROJECT_ROOT = Path('/content/drive/MyDrive/dissertation')
else:
    PROJECT_ROOT = Path('../../..').resolve()

sys.path.insert(0, str(PROJECT_ROOT))

print(f'IN_COLAB={IN_COLAB}')
print(f'PROJECT_ROOT={PROJECT_ROOT}')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
IN_COLAB=True
PROJECT_ROOT=/content/drive/MyDrive/dissertation

In [2]:
import hashlib
import json
import time

import numpy as np
import pandas as pd
import torch

from src import dataloader as data
from src import metrics
from src import train
from src.models.classical_baseline import HORIZONS
from src.models.multimodal_residual import load_frozen_baseline, FrozenImageOnlyResidualPredictor

ENCODER_NAME = 'resnet18'
IMG_FEAT_DIM = 512
EXPECTED_IMG_PROJ_DIM = 4

SEEDS = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]

EXP_DIR = PROJECT_ROOT / 'experiments' / '5_residual_hyper'

SHARED_CONFIG_PATH = EXP_DIR / 'shared_search' / 'multimodal_tuning_configurations.csv'

RESULTS_DIR = EXP_DIR / 'results' / ENCODER_NAME
CHECKPOINT_ROOT = EXP_DIR / 'checkpoints' / ENCODER_NAME

BASELINE_CHECKPOINT_DIR = PROJECT_ROOT / 'experiments' / '3_initial_multimodal' / 'multimodal' / 'checkpoints' / 'gated_cgm_time'

BASELINE_RESULTS_DIR = PROJECT_ROOT / 'experiments' / '3_initial_multimodal' / 'multimodal' / 'results' / 'gated_cgm_time'

SEED_RESULT_DIR = RESULTS_DIR / 'seed_results'
SUMMARY_DIR = RESULTS_DIR / 'summary'

for p in [RESULTS_DIR, SEED_RESULT_DIR, SUMMARY_DIR, CHECKPOINT_ROOT]:
    p.mkdir(parents=True, exist_ok=True)

TRIAL_TABLE_PATH = SUMMARY_DIR / 'resnet18_tuning_trials.csv'
BEST_CONFIG_PATH = SUMMARY_DIR / 'resnet18_best_config.json'
PARTICIPANT_TABLE_PATH = SUMMARY_DIR / 'resnet18_selected_config_participant_rmse.csv'

print('Shared configs:', SHARED_CONFIG_PATH)
print('Results:', RESULTS_DIR)

Shared configs: /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/shared_search/multimodal_tuning_configurations.csv
Results: /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/resnet18

In [3]:
configs = pd.read_csv(SHARED_CONFIG_PATH).sort_values('config_order').reset_index(drop=True)

required_cols = {
    'config_order', 'config_id', 'is_anchor',
    'img_proj_dim', 'img_dropout', 'lr', 'weight_decay'
}

expected_anchor = {
    'img_proj_dim': 4,
    'img_dropout': 0.3,
    'lr': 1e-4,
    'weight_decay': 1e-5,
}

anchor_rows = configs[configs['is_anchor'].astype(str).str.lower().isin(['true','1'])]
anchor = anchor_rows.iloc[0]
config_sha256 = hashlib.sha256(SHARED_CONFIG_PATH.read_bytes()).hexdigest()

print(f'Loaded {len(configs)} fixed configurations.')
print('CSV SHA256:', config_sha256)
display(configs)

Loaded 40 fixed configurations.
CSV SHA256: 32e220271d6157119aec540c96162224e751d9f49207f511dc6cb171c77434d3

,config_order,config_id,is_anchor,img_proj_dim,img_dropout,lr,weight_decay
0,1,cfg_01,True,4,0.3,0.00010,0.000010
1,2,cfg_02,False,4,0.1,0.00003,0.000000
2,3,cfg_03,False,4,0.5,0.00003,0.000010
3,4,cfg_04,False,4,0.1,0.00001,0.000001
4,5,cfg_05,False,4,0.3,0.00100,0.000000
5,6,cfg_06,False,4,0.5,0.00100,0.000001
6,7,cfg_07,False,4,0.5,0.00010,0.000001
7,8,cfg_08,False,4,0.1,0.00100,0.000001
8,9,cfg_09,False,4,0.0,0.00010,0.000100
9,10,cfg_10,False,4,0.5,0.00003,0.000100
10,11,cfg_11,False,4,0.0,0.00100,0.000010
11,12,cfg_12,False,4,0.3,0.00003,0.000000
12,13,cfg_13,False,4,0.0,0.00100,0.000100
13,14,cfg_14,False,4,0.5,0.00001,0.000001
14,15,cfg_15,False,4,0.3,0.00001,0.000100
15,16,cfg_16,False,4,0.0,0.00100,0.000001
16,17,cfg_17,False,4,0.0,0.00003,0.000000
17,18,cfg_18,False,4,0.5,0.00030,0.000010
18,19,cfg_19,False,4,0.1,0.00100,0.000100
19,20,cfg_20,False,4,0.3,0.00003,0.000001
20,21,cfg_21,False,4,0.5,0.00030,0.000000
21,22,cfg_22,False,4,0.3,0.00003,0.000010
22,23,cfg_23,False,4,0.0,0.00010,0.000000
23,24,cfg_24,False,4,0.0,0.00030,0.000010
24,25,cfg_25,False,4,0.3,0.00001,0.000001
25,26,cfg_26,False,4,0.1,0.00030,0.000001
26,27,cfg_27,False,4,0.3,0.00030,0.000100
27,28,cfg_28,False,4,0.1,0.00003,0.000001
28,29,cfg_29,False,4,0.3,0.00010,0.000100
29,30,cfg_30,False,4,0.1,0.00010,0.000100
30,31,cfg_31,False,4,0.0,0.00100,0.000000
31,32,cfg_32,False,4,0.0,0.00001,0.000000
32,33,cfg_33,False,4,0.1,0.00001,0.000010
33,34,cfg_34,False,4,0.3,0.00100,0.000010
34,35,cfg_35,False,4,0.3,0.00100,0.000001
35,36,cfg_36,False,4,0.0,0.00003,0.000001
36,37,cfg_37,False,4,0.1,0.00003,0.000010
37,38,cfg_38,False,4,0.1,0.00030,0.000010
38,39,cfg_39,False,4,0.3,0.00001,0.000000
39,40,cfg_40,False,4,0.1,0.00001,0.000000

In [4]:
stats = data.load_cgm_stats()

train_loader = data.load_multimodal_tensors('train', encoder_name=ENCODER_NAME)
val_loader = data.load_multimodal_tensors('val', encoder_name=ENCODER_NAME, shuffle=False)

val_participant_ids = data.load_multimodal_participant_ids('val')
VAL_PARTICIPANT_IDS = sorted(set(val_participant_ids))

print('n_train_batches:', len(train_loader))
print('n_val_batches:', len(val_loader))
print('n_val_samples:', len(val_loader.dataset))
print('validation participants:', VAL_PARTICIPANT_IDS)

sample_batch = next(iter(train_loader))
print('batch shapes:', [tuple(x.shape) for x in sample_batch])

n_train_batches: 323
n_val_batches: 64
n_val_samples: 16355
validation participants: [np.str_('CGMacros-005'), np.str_('CGMacros-016'), np.str_('CGMacros-027'), np.str_('CGMacros-044'), np.str_('CGMacros-046'), np.str_('CGMacros-048')]
batch shapes: [(256, 24), (256,), (256,), (256, 512), (256, 5)]

In [5]:
def forward_fn(model, batch, device):
    cgm, tsm, has_meal, img_feat, target = batch
    pred = model(cgm.to(device), tsm.to(device), img_feat.to(device), has_meal.to(device))
    return pred, target.to(device)


def h_entry(d, h):
    if str(h) in d:
        return d[str(h)]
    if h in d:
        return d[h]
    raise KeyError(f'Horizon {h} not found. Keys={list(d.keys())}')


def p_entry(d, pid):
    if str(pid) in d:
        return d[str(pid)]
    if pid in d:
        return d[pid]
    raise KeyError(f'Participant {pid} not found. Keys={list(d.keys())}')


def result_path(config_id, seed):
    return SEED_RESULT_DIR / f'{config_id}__seed{seed}.json'

In [6]:
baseline_by_seed = {}

for seed in SEEDS:
    path = BASELINE_RESULTS_DIR / f'gated_cgm_time_seed{seed}_results.json'
    if not path.exists():
        raise FileNotFoundError(f'Missing baseline result: {path}')

    with open(path) as f:
        r = json.load(f)

    baseline_by_seed[seed] = {
        int(h): float(h_entry(r['val_results'], h)['rmse'])
        for h in HORIZONS
    }

baseline_df = pd.DataFrame.from_dict(baseline_by_seed, orient='index')
baseline_df.index.name = 'seed'
baseline_df.columns = [f'rmse_{h}' for h in baseline_df.columns]

display(baseline_df.round(4))

      rmse_15  rmse_30  rmse_60  rmse_90  rmse_120
seed
7     10.5760  16.6694  24.0796  28.4527   31.2947
14    10.6479  16.7263  24.1044  28.3922   31.2335
21    10.5938  16.6580  24.0522  28.3216   31.1125
28    10.4778  16.5493  23.9988  28.4047   31.2741
35    10.4813  16.6073  24.1134  28.4409   31.2625
42    10.5140  16.6368  23.9722  28.3538   31.2148
49    10.6880  16.7477  24.0997  28.3797   31.1949
56    10.6339  16.7684  24.1647  28.4863   31.2816
63    10.5760  16.7480  24.0524  28.3896   31.2817
70    10.5711  16.6938  24.0569  28.3918   31.3112

In [7]:
CHECK_SEED = SEEDS[0]
CHECK_DROPOUT = float(anchor['img_dropout'])

base_model = load_frozen_baseline(CHECK_SEED, BASELINE_CHECKPOINT_DIR)

train.set_seed(CHECK_SEED)

check_model = FrozenImageOnlyResidualPredictor(
    base_model=base_model, img_feat_dim=IMG_FEAT_DIM, img_proj_dim=EXPECTED_IMG_PROJ_DIM, img_dropout=CHECK_DROPOUT)

baseline_trainable = [name for name, p in check_model.named_parameters()
                      if p.requires_grad and name.startswith(('gru.', 'time_proj.', 'base_head.'))]
if baseline_trainable:
    raise RuntimeError(f'Frozen baseline contains trainable parameters: {baseline_trainable}')

trainable_names = [name for name, p in check_model.named_parameters() if p.requires_grad]
print('Trainable parameters:')
for name in trainable_names:
    print(' ', name)

batch = next(iter(val_loader))
cgm, tsm, has_meal, img_feat, _ = batch

check_model.eval()
base_model.eval()
with torch.no_grad():
    base_pred = base_model(cgm, tsm, has_meal)
    residual_pred = check_model(cgm, tsm, img_feat, has_meal)

init_diff = (base_pred - residual_pred).abs().max().item()
print(f'Initial max |residual - baseline| = {init_diff:.8f}')

if init_diff > 1e-5:
    raise RuntimeError(f'Residual initialisation sanity check failed: {init_diff}')

print('Sanity checks passed.')

Trainable parameters:
  img_proj.0.weight
  img_proj.0.bias
  image_head.0.weight
  image_head.0.bias
  image_head.3.weight
  image_head.3.bias
Initial max |residual - baseline| = 0.00000000
Sanity checks passed.

In [8]:
batch = next(iter(train_loader))
cgm, tsm, has_meal, img_feat, target = batch

print('Encoder:', ENCODER_NAME)
print('Image feature shape:', img_feat.shape)

assert ENCODER_NAME == 'resnet18'
assert img_feat.shape[-1] == IMG_FEAT_DIM == 512

Encoder: resnet18
Image feature shape: torch.Size([256, 512])

In [ ]:
for config_idx, row in configs.iterrows():

    config_id = str(row['config_id'])
    img_proj_dim = int(row['img_proj_dim'])
    img_dropout = float(row['img_dropout'])
    lr = float(row['lr'])
    weight_decay = float(row['weight_decay'])

    print('\n' + '=' * 90)
    print(
        f'{config_id} ({config_idx + 1}/{len(configs)}) | '
        f'd={img_proj_dim} | dropout={img_dropout:g} | '
        f'lr={lr:g} | wd={weight_decay:g}'
    )
    print('=' * 90)

    for seed in SEEDS:

        save_path = result_path(config_id, seed)

        if save_path.exists():
            print(f'  seed={seed}: already complete')
            continue

        print(f'  seed={seed}: training')

        base_model = load_frozen_baseline(seed, BASELINE_CHECKPOINT_DIR)

        train.set_seed(seed)

        model = FrozenImageOnlyResidualPredictor(
            base_model=base_model, img_feat_dim=IMG_FEAT_DIM, img_proj_dim=img_proj_dim, img_dropout=img_dropout)

        baseline_trainable = [name for name, p in model.named_parameters()
                              if p.requires_grad and name.startswith(('gru.', 'time_proj.', 'base_head.'))]
        if baseline_trainable:
            raise RuntimeError(
                f'{config_id}, seed={seed}: baseline not fully frozen: '
                f'{baseline_trainable}'
            )

        # Verify zero-residual initialisation for every run.
        batch = next(iter(val_loader))
        cgm, tsm, has_meal, img_feat, _ = batch

        model.eval()
        base_model.eval()
        with torch.no_grad():
            base_pred = base_model(cgm, tsm, has_meal)
            residual_pred = model(cgm, tsm, img_feat, has_meal)

        init_diff = (base_pred - residual_pred).abs().max().item()
        if init_diff > 1e-5:
            raise RuntimeError(
                f'{config_id}, seed={seed}: initial residual != baseline '
                f'(max diff={init_diff})'
            )

        checkpoint_dir = CHECKPOINT_ROOT / config_id / f'seed_{seed}'

        t0 = time.time()

        model, history = train.train_model(
            model, train_loader, val_loader, stats['cgm_mean'], stats['cgm_std'], lr=lr, weight_decay=weight_decay,
            forward_fn=forward_fn, checkpoint_dir=checkpoint_dir, verbose=False, progress_bar=True, progress_desc=f'Resnet18 {config_id} seed={seed}')

        elapsed_seconds = time.time() - t0

        best_epoch = int(np.argmin(history['val_loss']) + 1)
        n_epochs_trained = int(len(history['train_loss']))

        y_pred_val, y_true_val = train.predict(model, val_loader, forward_fn=forward_fn)

        overall_val = metrics.evaluate(y_pred_val, y_true_val, stats['cgm_mean'], stats['cgm_std'])

        per_participant_val = metrics.evaluate_per_participant(
            y_pred_val, y_true_val, val_participant_ids, stats['cgm_mean'], stats['cgm_std'])

        # Ensure all expected validation participants were produced.
        for pid in VAL_PARTICIPANT_IDS:
            _ = p_entry(per_participant_val, pid)

        payload = {
            'encoder': ENCODER_NAME,
            'config_id': config_id,
            'config_order': int(row['config_order']),
            'is_anchor': bool(str(row['is_anchor']).lower() in ['true', '1']),
            'shared_config_sha256': config_sha256,
            'seed': int(seed),
            'hyperparameters': {
                'img_proj_dim': img_proj_dim,
                'img_dropout': img_dropout,
                'lr': lr,
                'weight_decay': weight_decay,
            },
            'initial_max_abs_diff_vs_baseline': float(init_diff),
            'best_epoch': best_epoch,
            'n_epochs_trained': n_epochs_trained,
            'elapsed_seconds': float(elapsed_seconds),
            'val_results': overall_val,
            'val_results_per_participant': per_participant_val,
        }

        with open(save_path, 'w') as f:
            json.dump(payload, f, indent=2)

        print(
            f'    saved | best_epoch={best_epoch} | '
            f'{elapsed_seconds/60:.1f} min'
        )

print('\nAll requested Resnet18 tuning runs are complete.')

==========================================================================================
cfg_01 (1/40) | d=4 | dropout=0.3 | lr=0.0001 | wd=1e-05
==========================================================================================
  seed=7: already complete
  seed=14: already complete
  seed=21: already complete
  seed=28: already complete
  seed=35: already complete
  seed=42: already complete
  seed=49: already complete
  seed=56: already complete
  seed=63: already complete
  seed=70: already complete

==========================================================================================
cfg_02 (2/40) | d=4 | dropout=0.1 | lr=3e-05 | wd=0
==========================================================================================
  seed=7: already complete
  seed=14: already complete
  seed=21: already complete
  seed=28: already complete
  seed=35: already complete
  seed=42: already complete
  seed=49: already complete
  seed=56: already complete
  seed=63: already complete
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_02 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min

==========================================================================================
cfg_03 (3/40) | d=4 | dropout=0.5 | lr=3e-05 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=27 | 0.7 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=17 | 0.5 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=18 | 0.6 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=15 | 0.5 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_03 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min

==========================================================================================
cfg_04 (4/40) | d=4 | dropout=0.1 | lr=1e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.6 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=27 | 0.7 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=32 | 0.8 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=29 | 0.8 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=31 | 0.8 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_04 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min

==========================================================================================
cfg_05 (5/40) | d=4 | dropout=0.3 | lr=0.001 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_05 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_06 (6/40) | d=4 | dropout=0.5 | lr=0.001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_06 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_07 (7/40) | d=4 | dropout=0.5 | lr=0.0001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_07 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min

==========================================================================================
cfg_08 (8/40) | d=4 | dropout=0.1 | lr=0.001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_08 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_09 (9/40) | d=4 | dropout=0 | lr=0.0001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_09 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_10 (10/40) | d=4 | dropout=0.5 | lr=3e-05 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=15 | 0.5 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=13 | 0.5 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=18 | 0.6 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=15 | 0.5 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_10 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min

==========================================================================================
cfg_11 (11/40) | d=4 | dropout=0 | lr=0.001 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_11 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_12 (12/40) | d=4 | dropout=0.3 | lr=3e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_12 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min

==========================================================================================
cfg_13 (13/40) | d=4 | dropout=0 | lr=0.001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_13 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_14 (14/40) | d=4 | dropout=0.5 | lr=1e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=43 | 1.0 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=40 | 1.0 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=49 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=47 | 1.0 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=46 | 1.0 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_14 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=35 | 0.9 min

==========================================================================================
cfg_15 (15/40) | d=4 | dropout=0.3 | lr=1e-05 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=34 | 0.9 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=38 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=38 | 1.0 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=38 | 1.0 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=25 | 0.7 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_15 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min

==========================================================================================
cfg_16 (16/40) | d=4 | dropout=0 | lr=0.001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_16 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_17 (17/40) | d=4 | dropout=0 | lr=3e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_17 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min

==========================================================================================
cfg_18 (18/40) | d=4 | dropout=0.5 | lr=0.0003 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_18 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min

==========================================================================================
cfg_19 (19/40) | d=4 | dropout=0.1 | lr=0.001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_19 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_20 (20/40) | d=4 | dropout=0.3 | lr=3e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_20 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min

==========================================================================================
cfg_21 (21/40) | d=4 | dropout=0.5 | lr=0.0003 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_21 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min

==========================================================================================
cfg_22 (22/40) | d=4 | dropout=0.3 | lr=3e-05 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=12 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_22 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min

==========================================================================================
cfg_23 (23/40) | d=4 | dropout=0 | lr=0.0001 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_23 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_24 (24/40) | d=4 | dropout=0 | lr=0.0003 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_24 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_25 (25/40) | d=4 | dropout=0.3 | lr=1e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=34 | 0.9 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=38 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=34 | 0.9 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=38 | 1.0 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=25 | 0.7 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_25 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min

==========================================================================================
cfg_26 (26/40) | d=4 | dropout=0.1 | lr=0.0003 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_26 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_27 (27/40) | d=4 | dropout=0.3 | lr=0.0003 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_27 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_28 (28/40) | d=4 | dropout=0.1 | lr=3e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_28 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min

==========================================================================================
cfg_29 (29/40) | d=4 | dropout=0.3 | lr=0.0001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_29 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min

==========================================================================================
cfg_30 (30/40) | d=4 | dropout=0.1 | lr=0.0001 | wd=0.0001
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=3 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_30 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_31 (31/40) | d=4 | dropout=0 | lr=0.001 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_31 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_32 (32/40) | d=4 | dropout=0 | lr=1e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=14 | 0.5 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=20 | 0.6 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=19 | 0.6 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=24 | 0.7 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=20 | 0.6 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=19 | 0.6 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=24 | 0.7 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_32 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=19 | 0.6 min

==========================================================================================
cfg_33 (33/40) | d=4 | dropout=0.1 | lr=1e-05 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.6 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=27 | 0.8 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=33 | 0.9 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=29 | 0.8 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=31 | 0.8 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_33 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min

==========================================================================================
cfg_34 (34/40) | d=4 | dropout=0.3 | lr=0.001 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_34 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_35 (35/40) | d=4 | dropout=0.3 | lr=0.001 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_35 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=2 | 0.2 min

==========================================================================================
cfg_36 (36/40) | d=4 | dropout=0 | lr=3e-05 | wd=1e-06
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.3 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=6 | 0.3 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_36 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min

==========================================================================================
cfg_37 (37/40) | d=4 | dropout=0.1 | lr=3e-05 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.4 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=10 | 0.4 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=8 | 0.4 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=7 | 0.4 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=11 | 0.4 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=9 | 0.4 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=4 | 0.3 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_37 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=5 | 0.3 min

==========================================================================================
cfg_38 (38/40) | d=4 | dropout=0.1 | lr=0.0003 | wd=1e-05
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_38 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=1 | 0.2 min

==========================================================================================
cfg_39 (39/40) | d=4 | dropout=0.3 | lr=1e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=33 | 0.9 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=50 | 1.0 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=38 | 1.0 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=34 | 0.9 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=48 | 1.0 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=38 | 1.0 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=25 | 0.7 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_39 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min

==========================================================================================
cfg_40 (40/40) | d=4 | dropout=0.1 | lr=1e-05 | wd=0
==========================================================================================
  seed=7: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=7:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=22 | 0.7 min
  seed=14: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=14:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=27 | 0.8 min
  seed=21: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=21:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=28: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=28:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=30 | 0.8 min
  seed=35: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=35:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=26 | 0.7 min
  seed=42: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=42:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min
  seed=49: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=49:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=29 | 0.8 min
  seed=56: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=56:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=33 | 0.9 min
  seed=63: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=63:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=16 | 0.5 min
  seed=70: training
device: cuda (NVIDIA RTX PRO 6000 Blackwell Server Edition)  model: FrozenImageOnlyResidualPredictor  params: 1,028,478

Resnet18 cfg_40 seed=70:   0%|          | 0/50 [00:00<?, ?it/s]

    saved | best_epoch=23 | 0.7 min

All requested Resnet18 tuning runs are complete.

In [ ]:
trial_rows = []
participant_rows_all = []

for _, cfg in configs.iterrows():

    config_id = str(cfg['config_id'])
    seed_results = []

    for seed in SEEDS:
        with open(result_path(config_id, seed)) as f:
            r = json.load(f)

        if r.get('shared_config_sha256') != config_sha256:
            raise RuntimeError(
                f'{config_id}, seed={seed} was produced from a different '
                'shared configuration file.'
            )

        seed_results.append(r)

    row = {
        'config_order': int(cfg['config_order']),
        'config_id': config_id,
        'is_anchor': bool(str(cfg['is_anchor']).lower() in ['true', '1']),
        'img_proj_dim': int(cfg['img_proj_dim']),
        'img_dropout': float(cfg['img_dropout']),
        'lr': float(cfg['lr']),
        'weight_decay': float(cfg['weight_decay']),
    }

    all_relative_improvements = []
    improved_horizon_seed_pairs = 0
    all_absolute_rmses = []

    for h in HORIZONS:

        candidate = np.asarray([float(h_entry(r['val_results'], h)['rmse']) for r in seed_results])

        baseline = np.asarray([baseline_by_seed[seed][int(h)] for seed in SEEDS])

        improvement_pct = (baseline - candidate) / baseline * 100.0

        # Participant means across seeds, then SD across participants.
        participant_means = []

        for pid in VAL_PARTICIPANT_IDS:
            pid_seed_rmses = [
                float(h_entry(p_entry(r['val_results_per_participant'], pid), h)['rmse']) for r in seed_results]

            pid_mean = float(np.mean(pid_seed_rmses))
            participant_means.append(pid_mean)

            participant_rows_all.append({
                'config_id': config_id,
                'participant_id': pid,
                'horizon': int(h),
                'mean_rmse_across_seeds': pid_mean,
                'sd_rmse_across_seeds': float(np.std(pid_seed_rmses, ddof=1)),
            })

        rmse_mean = float(np.mean(candidate))
        sd1 = float(np.std(candidate, ddof=1))
        sd2 = float(np.std(participant_means, ddof=1))
        wins = int(np.sum(candidate < baseline))

        row[f'rmse_{h}'] = rmse_mean
        row[f'sd1_{h}'] = sd1
        row[f'sd2_{h}'] = sd2
        row[f'improvement_pct_{h}'] = float(np.mean(improvement_pct))
        row[f'improved_seeds_{h}'] = wins

        all_relative_improvements.extend(improvement_pct.tolist())
        improved_horizon_seed_pairs += wins
        all_absolute_rmses.extend(candidate.tolist())

    row['mean_relative_improvement_pct'] = float(
        np.mean(all_relative_improvements)
    )
    row['improved_horizon_seed_pairs'] = int(improved_horizon_seed_pairs)
    row['mean_validation_rmse'] = float(np.mean(all_absolute_rmses))

    trial_rows.append(row)

trial_df = pd.DataFrame(trial_rows)
participant_df = pd.DataFrame(participant_rows_all)

trial_df.to_csv(TRIAL_TABLE_PATH, index=False)

print('Saved complete tuning table:')
print(TRIAL_TABLE_PATH)

display(
    trial_df[
        [
            'config_order','config_id','is_anchor',
            'img_dropout','lr','weight_decay',
            'mean_relative_improvement_pct',
            'improved_horizon_seed_pairs',
            'mean_validation_rmse',
            *[f'rmse_{h}' for h in HORIZONS],
        ]
    ].round(5)
)

Saved complete tuning table:
/content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/resnet18/summary/resnet18_tuning_trials.csv

,config_order,config_id,is_anchor,img_dropout,lr,weight_decay,mean_relative_improvement_pct,improved_horizon_seed_pairs,mean_validation_rmse,rmse_15,rmse_30,rmse_60,rmse_90,rmse_120
0,1,cfg_01,True,0.3,0.00010,0.00001,0.38823,50,22.09540,10.55932,16.64260,23.96687,28.25926,31.04893
1,2,cfg_02,False,0.1,0.00003,0.00000,0.43703,50,22.08175,10.55856,16.64083,23.95670,28.23970,31.01297
2,3,cfg_03,False,0.5,0.00003,0.00001,0.31457,50,22.11517,10.56086,16.64828,23.98485,28.28806,31.09378
3,4,cfg_04,False,0.1,0.00001,0.00000,0.42002,50,22.08629,10.55920,16.64182,23.95981,28.24768,31.02294
4,5,cfg_05,False,0.3,0.00100,0.00000,0.26721,49,22.12922,10.56023,16.64788,23.99230,28.31879,31.12691
5,6,cfg_06,False,0.5,0.00100,0.00000,0.28982,49,22.12135,10.56203,16.65398,23.98732,28.28922,31.11419
6,7,cfg_07,False,0.5,0.00010,0.00000,0.32018,50,22.11410,10.56017,16.64703,23.98268,28.28536,31.09524
7,8,cfg_08,False,0.1,0.00100,0.00000,0.01915,30,22.19274,10.56640,16.67351,24.07542,28.42982,31.21858
8,9,cfg_09,False,0.0,0.00010,0.00010,0.43484,50,22.08134,10.56050,16.64284,23.95669,28.23957,31.00711
9,10,cfg_10,False,0.5,0.00003,0.00010,0.31357,50,22.11558,10.56068,16.64799,23.98490,28.28865,31.09571
10,11,cfg_11,False,0.0,0.00100,0.00001,-0.20102,12,22.24772,10.57354,16.70198,24.14481,28.52164,31.29664
11,12,cfg_12,False,0.3,0.00003,0.00000,0.37723,50,22.09822,10.55954,16.64399,23.97016,28.26383,31.05357
12,13,cfg_13,False,0.0,0.00100,0.00010,-0.11483,19,22.22535,10.57126,16.69488,24.11709,28.48356,31.25996
13,14,cfg_14,False,0.5,0.00001,0.00000,0.29423,50,22.12008,10.56178,16.65120,23.99171,28.29573,31.09998
14,15,cfg_15,False,0.3,0.00001,0.00010,0.37831,50,22.09828,10.55913,16.64279,23.96898,28.26578,31.05470
15,16,cfg_16,False,0.0,0.00100,0.00000,-0.24304,15,22.26143,10.57451,16.69455,24.14130,28.55127,31.34551
16,17,cfg_17,False,0.0,0.00003,0.00000,0.43954,50,22.07982,10.56046,16.64372,23.95624,28.23594,31.00275
17,18,cfg_18,False,0.5,0.00030,0.00001,0.30674,50,22.11734,10.56124,16.64901,23.98517,28.28812,31.10314
18,19,cfg_19,False,0.1,0.00100,0.00010,0.00273,27,22.19698,10.56761,16.67605,24.07312,28.43444,31.23367
19,20,cfg_20,False,0.3,0.00003,0.00000,0.37775,50,22.09811,10.55946,16.64387,23.97007,28.26372,31.05343
20,21,cfg_21,False,0.5,0.00030,0.00000,0.29781,50,22.12000,10.56130,16.64873,23.98651,28.29189,31.11159
21,22,cfg_22,False,0.3,0.00003,0.00001,0.38221,50,22.09706,10.55936,16.64309,23.96777,28.26224,31.05282
22,23,cfg_23,False,0.0,0.00010,0.00000,0.44049,50,22.08006,10.55983,16.64212,23.95567,28.23723,31.00547
23,24,cfg_24,False,0.0,0.00030,0.00001,0.38588,50,22.09630,10.55814,16.64178,23.97049,28.27080,31.04027
24,25,cfg_25,False,0.3,0.00001,0.00000,0.36623,50,22.10123,10.55974,16.64437,23.97251,28.27021,31.05931
25,26,cfg_26,False,0.1,0.00030,0.00000,0.40809,50,22.09072,10.55777,16.63915,23.96252,28.25568,31.03847
26,27,cfg_27,False,0.3,0.00030,0.00010,0.39036,50,22.09509,10.55950,16.64166,23.96315,28.25789,31.05324
27,28,cfg_28,False,0.1,0.00003,0.00000,0.43442,50,22.08241,10.55871,16.64115,23.95722,28.24043,31.01454
28,29,cfg_29,False,0.3,0.00010,0.00010,0.39379,50,22.09402,10.55909,16.64187,23.96526,28.25713,31.04675
29,30,cfg_30,False,0.1,0.00010,0.00010,0.43423,50,22.08313,10.55877,16.63845,23.95351,28.24161,31.02332
30,31,cfg_31,False,0.0,0.00100,0.00000,-0.27660,11,22.26376,10.58115,16.71806,24.16739,28.54456,31.30764
31,32,cfg_32,False,0.0,0.00001,0.00000,0.42128,50,22.08524,10.56015,16.64333,23.96079,28.24604,31.01591
32,33,cfg_33,False,0.1,0.00001,0.00001,0.42062,50,22.08622,10.55914,16.64154,23.95905,28.24738,31.02400
33,34,cfg_34,False,0.3,0.00100,0.00001,0.27468,49,22.12784,10.55914,16.64580,23.99053,28.31628,31.12744
34,35,cfg_35,False,0.3,0.00100,0.00000,0.26119,47,22.13107,10.56010,16.64757,23.99387,28.32133,31.13246
35,36,cfg_36,False,0.0,0.00003,0.00000,0.43876,50,22.08002,10.56049,16.64368,23.95677,28.23661,31.00255
36,37,cfg_37,False,0.1,0.00003,0.00001,0.43344,50,22.08269,10.55871,16.64121,23.95721,28.24096,31.01537
37,38,cfg_38,False,0.1,0.00030,0.00001,0.43421,50,22.08413,10.55693,16.63600,23.95438,28.24561,31.02774
38,39,cfg_39,False,0.3,0.00001,0.00000,0.36628,50,22.10122,10.55974,16.64437,23.97251,28.27011,31.05937
39,40,cfg_40,False,0.1,0.00001,0.00000,0.42236,50,22.08569,10.55912,16.64152,23.95923,28.24661,31.02198

In [ ]:
ranked_df = trial_df.sort_values(
    by=['mean_relative_improvement_pct', 'improved_horizon_seed_pairs', 'mean_validation_rmse', 'config_order'],
    ascending=[False, False, True, True]).reset_index(drop=True)

ranked_df.insert(0, 'rank', np.arange(1, len(ranked_df) + 1))

display(
    ranked_df[
        [
            'rank','config_id','is_anchor',
            'img_dropout','lr','weight_decay',
            'mean_relative_improvement_pct',
            'improved_horizon_seed_pairs',
            'mean_validation_rmse',
            *[f'rmse_{h}' for h in HORIZONS],
            *[f'sd1_{h}' for h in HORIZONS],
            *[f'sd2_{h}' for h in HORIZONS],
        ]
    ].round(5)
)

best = ranked_df.iloc[0]
best_config_id = str(best['config_id'])

best_payload = {
    'encoder': ENCODER_NAME,
    'shared_config_sha256': config_sha256,
    'selection_data': 'validation only',
    'selection_rule': {
        'primary': (
            'maximise mean relative RMSE improvement versus seed-matched '
            'CGM+Time across all five horizons and ten seeds'
        ),
        'tie_breaker_1': 'maximise improved horizon-seed pairs',
        'tie_breaker_2': 'minimise mean validation RMSE',
        'tie_breaker_3': 'lower config_order',
    },
    'selected': {
        'config_id': best_config_id,
        'config_order': int(best['config_order']),
        'img_proj_dim': int(best['img_proj_dim']),
        'img_dropout': float(best['img_dropout']),
        'lr': float(best['lr']),
        'weight_decay': float(best['weight_decay']),
        'mean_relative_improvement_pct': float(best['mean_relative_improvement_pct']),
        'improved_horizon_seed_pairs': int(best['improved_horizon_seed_pairs']),
        'mean_validation_rmse': float(best['mean_validation_rmse']),
    },
    'horizons': {},
}

for h in HORIZONS:
    best_payload['horizons'][str(h)] = {
        'rmse_mean': float(best[f'rmse_{h}']),
        'sd1_across_seeds': float(best[f'sd1_{h}']),
        'sd2_across_participants': float(best[f'sd2_{h}']),
        'mean_improvement_pct_vs_cgm_time': float(best[f'improvement_pct_{h}']),
        'improved_seeds_vs_cgm_time': int(best[f'improved_seeds_{h}']),
    }

with open(BEST_CONFIG_PATH, 'w') as f:
    json.dump(best_payload, f, indent=2)

selected_participant_df = participant_df[participant_df['config_id'] == best_config_id].copy()

selected_participant_df.to_csv(PARTICIPANT_TABLE_PATH, index=False)

print('\n=== SELECTED CLIP CONFIGURATION ===')
print('config_id:', best_config_id)
print('dropout:', best['img_dropout'])
print('lr:', best['lr'])
print('weight_decay:', best['weight_decay'])
print(
    'mean relative improvement:',
    f"{best['mean_relative_improvement_pct']:.4f}%"
)
print(
    'improved horizon-seed pairs:',
    f"{int(best['improved_horizon_seed_pairs'])}/{len(HORIZONS)*len(SEEDS)}"
)

print('\nPer-horizon validation result: mean ± sd1 (sd2)')
for h in HORIZONS:
    print(
        f'{h:>3} min: '
        f"{best[f'rmse_{h}']:.3f} ± "
        f"{best[f'sd1_{h}']:.3f} "
        f"({best[f'sd2_{h}']:.3f}) | "
        f"improvement={best[f'improvement_pct_{h}']:.3f}% | "
        f"better seeds={int(best[f'improved_seeds_{h}'])}/{len(SEEDS)}"
    )

print('\nSaved:')
print(' ', TRIAL_TABLE_PATH)
print(' ', BEST_CONFIG_PATH)
print(' ', PARTICIPANT_TABLE_PATH)

,rank,config_id,is_anchor,img_dropout,lr,weight_decay,mean_relative_improvement_pct,improved_horizon_seed_pairs,mean_validation_rmse,rmse_15,...,sd1_15,sd1_30,sd1_60,sd1_90,sd1_120,sd2_15,sd2_30,sd2_60,sd2_90,sd2_120
0,1,cfg_23,False,0.0,0.00010,0.00000,0.44049,50,22.08006,10.55983,...,0.05924,0.06571,0.05994,0.05726,0.07968,2.08050,3.57904,6.95886,10.12480,11.93882
1,2,cfg_17,False,0.0,0.00003,0.00000,0.43954,50,22.07982,10.56046,...,0.05874,0.06573,0.05756,0.05413,0.07110,2.07799,3.57688,6.96088,10.12826,11.94471
2,3,cfg_36,False,0.0,0.00003,0.00000,0.43876,50,22.08002,10.56049,...,0.05866,0.06552,0.05560,0.05292,0.07001,2.07781,3.57649,6.95979,10.12623,11.94194
3,4,cfg_02,False,0.1,0.00003,0.00000,0.43703,50,22.08175,10.55856,...,0.05903,0.06537,0.05427,0.04661,0.06747,2.07992,3.58026,6.95924,10.12627,11.94572
4,5,cfg_09,False,0.0,0.00010,0.00010,0.43484,50,22.08134,10.56050,...,0.06008,0.06648,0.05712,0.05395,0.07938,2.08004,3.57934,6.96671,10.13646,11.95202
5,6,cfg_28,False,0.1,0.00003,0.00000,0.43442,50,22.08241,10.55871,...,0.05907,0.06587,0.05480,0.04850,0.07090,2.07993,3.58056,6.96084,10.13033,11.95237
6,7,cfg_30,False,0.1,0.00010,0.00010,0.43423,50,22.08313,10.55877,...,0.06144,0.06755,0.05113,0.05092,0.07211,2.08094,3.58245,6.96904,10.14789,11.97548
7,8,cfg_38,False,0.1,0.00030,0.00001,0.43421,50,22.08413,10.55693,...,0.06050,0.06793,0.05595,0.05518,0.07396,2.08224,3.58286,6.96673,10.13677,11.96223
8,9,cfg_37,False,0.1,0.00003,0.00001,0.43344,50,22.08269,10.55871,...,0.05907,0.06581,0.05507,0.04920,0.07052,2.07990,3.58078,6.96254,10.13288,11.95507
9,10,cfg_40,False,0.1,0.00001,0.00000,0.42236,50,22.08569,10.55912,...,0.05911,0.06371,0.05219,0.04261,0.05753,2.08024,3.58169,6.97005,10.14296,11.96672
10,11,cfg_32,False,0.0,0.00001,0.00000,0.42128,50,22.08524,10.56015,...,0.05875,0.06505,0.05458,0.04930,0.06929,2.07764,3.57651,6.96538,10.13443,11.95498
11,12,cfg_33,False,0.1,0.00001,0.00001,0.42062,50,22.08622,10.55914,...,0.05919,0.06393,0.05182,0.04228,0.05580,2.08004,3.58162,6.97064,10.14438,11.96959
12,13,cfg_04,False,0.1,0.00001,0.00000,0.42002,50,22.08629,10.55920,...,0.05920,0.06395,0.05188,0.04255,0.05654,2.08002,3.58129,6.96952,10.14196,11.96590
13,14,cfg_26,False,0.1,0.00030,0.00000,0.40809,50,22.09072,10.55777,...,0.05991,0.06660,0.05815,0.05540,0.07158,2.08133,3.58231,6.96724,10.13662,11.96131
14,15,cfg_29,False,0.3,0.00010,0.00010,0.39379,50,22.09402,10.55909,...,0.05924,0.06531,0.05020,0.04346,0.06747,2.08228,3.58748,6.97305,10.15014,11.98375
15,16,cfg_27,False,0.3,0.00030,0.00010,0.39036,50,22.09509,10.55950,...,0.06056,0.06753,0.05697,0.04520,0.06783,2.08240,3.58790,6.97904,10.16338,12.00108
16,17,cfg_01,True,0.3,0.00010,0.00001,0.38823,50,22.09540,10.55932,...,0.05895,0.06496,0.04869,0.04377,0.06974,2.08198,3.58686,6.97313,10.14970,11.98331
17,18,cfg_24,False,0.0,0.00030,0.00001,0.38588,50,22.09630,10.55814,...,0.06037,0.07120,0.05880,0.07820,0.09518,2.07908,3.57236,6.94428,10.10368,11.91921
18,19,cfg_22,False,0.3,0.00003,0.00001,0.38221,50,22.09706,10.55936,...,0.05994,0.06574,0.04795,0.03353,0.05981,2.08272,3.58852,6.98551,10.17359,12.01266
19,20,cfg_15,False,0.3,0.00001,0.00010,0.37831,50,22.09828,10.55913,...,0.06041,0.06534,0.05451,0.03687,0.05452,2.08351,3.58941,6.98773,10.17365,12.00866
20,21,cfg_20,False,0.3,0.00003,0.00000,0.37775,50,22.09811,10.55946,...,0.05993,0.06608,0.04893,0.03488,0.06293,2.08291,3.58862,6.98397,10.17140,12.00975
21,22,cfg_12,False,0.3,0.00003,0.00000,0.37723,50,22.09822,10.55954,...,0.05990,0.06605,0.04874,0.03447,0.06251,2.08288,3.58854,6.98407,10.17145,12.00974
22,23,cfg_39,False,0.3,0.00001,0.00000,0.36628,50,22.10122,10.55974,...,0.05952,0.06458,0.05030,0.03285,0.05177,2.08298,3.58841,6.98787,10.17364,12.00934
23,24,cfg_25,False,0.3,0.00001,0.00000,0.36623,50,22.10123,10.55974,...,0.05949,0.06453,0.05005,0.03286,0.05171,2.08296,3.58837,6.98781,10.17340,12.00888
24,25,cfg_07,False,0.5,0.00010,0.00000,0.32018,50,22.11410,10.56017,...,0.05999,0.06599,0.05263,0.04431,0.06390,2.08597,3.59562,6.99392,10.19371,12.04667
25,26,cfg_03,False,0.5,0.00003,0.00001,0.31457,50,22.11517,10.56086,...,0.05979,0.06428,0.04897,0.03262,0.05516,2.08524,3.59421,6.99655,10.19530,12.04628
26,27,cfg_10,False,0.5,0.00003,0.00010,0.31357,50,22.11558,10.56068,...,0.05981,0.06410,0.04854,0.03156,0.05503,2.08568,3.59589,6.99821,10.19727,12.04910
27,28,cfg_18,False,0.5,0.00030,0.00001,0.30674,50,22.11734,10.56124,...,0.06027,0.06558,0.05989,0.05509,0.07031,2.08594,3.59644,6.99517,10.19574,12.05259
28,29,cfg_21,False,0.5,0.00030,0.00000,0.29781,50,22.12000,10.56130,...,0.06067,0.06823,0.05269,0.04989,0.07494,2.08581,3.59573,6.99333,10.19761,12.05764
29,30,cfg_14,False,0.5,0.00001,0.00000,0.29423,50,22.12008,10.56178,...,0.06010,0.06402,0.04880,0.02957,0.05352,2.08551,3.59549,7.00413,10.20725,12.05971
30,31,cfg_06,False,0.5,0.00100,0.00000,0.28982,49,22.12135,10.56203,...,0.06196,0.07379,0.08006,0.09344,0.12279,2.08416,3.58427,6.95367,10.14179,12.00218
31,32,cfg_34,False,0.3,0.00100,0.00001,0.27468,49,22.12784,10.55914,...,0.05928,0.06151,0.05206,0.06891,0.08399,2.08205,3.58669,6.98578,10.18420,12.04303
32,33,cfg_05,False,0.3,0.00100,0.00000,0.26721,49,22.12922,10.56023,...,0.06003,0.06162,0.05412,0.07050,0.08113,2.08329,3.58776,6.98000,10.17514,12.03405
33,34,cfg_35,False,0.3,0.00100,0.00000,0.26119,47,22.13107,10.56010,...,0.05933,0.06284,0.06099,0.08584,0.10177,2.07946,3.57928,6.97495,10.16722,12.02346
34,35,cfg_08,False,0.1,0.00100,0.00000,0.01915,30,22.19274,10.56640,...,0.06371,0.08200,0.10487,0.14806,0.16732,2.08045,3.57598,6.94056,10.10648,11.95192
35,36,cfg_19,False,0.1,0.00100,0.00010,0.00273,27,22.19698,10.56761,...,0.06456,0.08141,0.09839,0.14602,0.15991,2.07833,3.57150,6.95200,10.12493,11.97412
36,37,cfg_13,False,0.0,0.00100,0.00010,-0.11483,19,22.22535,10.57126,...,0.06262,0.08597,0.11403,0.17776,0.18929,2.08127,3.57167,6.94532,10.11007,11.94841
37,38,cfg_11,False,0.0,0.00100,0.00001,-0.20102,12,22.24772,10.57354,...,0.06063,0.07650,0.08523,0.13247,0.14389,2.08014,3.56913,6.94402,10.10476,11.94013
38,39,cfg_16,False,0.0,0.00100,0.00000,-0.24304,15,22.26143,10.57451,...,0.06638,0.08772,0.10210,0.16662,0.18794,2.08188,3.57069,6.94617,10.12272,11.96694
39,40,cfg_31,False,0.0,0.00100,0.00000,-0.27660,11,22.26376,10.58115,...,0.06251,0.08177,0.10362,0.14535,0.15989,2.08032,3.55830,6.90778,10.06498,11.90055

=== SELECTED CLIP CONFIGURATION ===
config_id: cfg_23
dropout: 0.0
lr: 0.0001
weight_decay: 0.0
mean relative improvement: 0.4405%
improved horizon-seed pairs: 50/50

Per-horizon validation result: mean ± sd1 (sd2)
 15 min: 10.560 ± 0.059 (2.081) | improvement=0.152% | better seeds=10/10
 30 min: 16.642 ± 0.066 (3.579) | improvement=0.230% | better seeds=10/10
 60 min: 23.956 ± 0.060 (6.959) | improvement=0.473% | better seeds=10/10
 90 min: 28.237 ± 0.057 (10.125) | improvement=0.578% | better seeds=10/10
120 min: 31.005 ± 0.080 (11.939) | improvement=0.770% | better seeds=10/10

Saved:
  /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/resnet18/summary/resnet18_tuning_trials.csv
  /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/resnet18/summary/resnet18_best_config.json
  /content/drive/MyDrive/dissertation/experiments/5_residual_hyper/results/resnet18/summary/resnet18_selected_config_participant_rmse.csv